### ISSUE TITLE
Switch to Operator Mono for all the code samples

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components-website#12]
Because I ❤️  it. I also have a webfont license for it 😄 

This is just a note for me or @superhighfives to hook this up soon.

**Comment by mxstbr** [comment]
> I also have a webfont license for it

Me === jelly af

**Comment by philpl** [comment]
Awesome! I'd do it myself, but I don't have the web licence :(

**Comment by superhighfives** [comment]
No worries. Will sort it out today. 👍

**Comment by superhighfives** [comment]
Okay, added: https://github.com/superhighfives/styled-components-website/tree/feature/%2312_operator_mono_for_code

[cloud.typography](https://www.typography.com/cloud/welcome/), which manages the Operator webfont, use a `<link />` to grab the fonts:
```
<link rel="stylesheet" type="text/css" href="https://cloud.typography.com/7039052/7606172/css/fonts.css" />
```

Once the project is ready to go to production, cloud.typography requires you to place the fonts on your server. It's a bit convoluted, but you can read about it here: https://dashboard.typography.com/user-guide/moving-to-production

The current branch is in development mode.

**Comment by philpl** [comment]
@superhighfives Shall we move it to production mode, so we can get the branch merged? :)

**Comment by superhighfives** [comment]
No worries!

![image](https://cloud.githubusercontent.com/assets/449385/26349400/74be1042-3fa7-11e7-965b-8045465e79ed.png)

So cloud.typography looks for the font files (they're generated for a specific URL) in order to enable production mode. You can effectively leave this in place until you're ready to flick the switch, as it will continue to use the development set up for now.
