### ISSUE TITLE
Upgrade to Next@4 with React@16

### ISSUE THREAD

**Issue by morajabi** [styled-components/styled-components-website#140]

**Comment by ishankbahl** [comment]
@mxstbr I would like to work on this one.

**Comment by mxstbr** [comment]
Do it!

**Comment by vtserman** [comment]
Oh, I was going to work on this 'good first issue'.
But anyway, I've done some initial investigation today. 
Since Next.js 4 requires React 16:
- You will not be able to use preact-compat in production mode any more.
- You will need to upgrade Enzyme to v3 and update snapshots for the tests to pass.

**Comment by ishankbahl** [comment]
@vtserman What changes are to be made for the preact-compat issue?
Saw your comment after making the PR. Though upgraded Enzyme and updated snapshots.

**Comment by vtserman** [comment]
Current version uses Preact for the production where it gives better performance, but since you upgraded to Next@4 with React@16 you will get an error "Error: Next.js 4 requires React 16." when trying to start application in production mode.
Use next.config.js to customize webpack config to turn off support of preact-compat

**Comment by philpl** [comment]
@ishankbahl let's wait until Next provides support for preact again. We wouldn't gain anything from upgrading to React 16 right now, and Streamed SSR is not interesting for us anyway, as all SSR routes are cached.

**Comment by imbhargav5** [comment]
Upgraded to Next@7 and React@16
