### ISSUE TITLE
Jump to Section, even if it has subsections, from sidebar

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#188]
Based on the discussion in #143 we should make it so that clicking on a section in the sidebar, even if it contains subsections, jumps to that section, instead of just showing its subsections.

**Comment by chinesedfan** [comment]
Tested with https://github.com/zeit/next.js/pull/2223. It works, but requires us to update next to at least v3.0.2.

**Comment by syneva-runyan** [comment]
I took a look at this issue some, and there are two parts of the problem:

1) The <Link> being used from next/link has an e.preventDefault() being called on click, which blocks the default scroll behavior

2) When the <Link> is replaced with a normal <a> tag, such as what's used with StyledLink, the scroll happens, but the onRouteChange called when <Section> is clicked updates the  <Folder> component via the componentWillReceivedProps AFTER the toggleSubsection update, but BEFORE  window.location.href has been update. Therefore, the isOpenDefault prop that should expand any section's subsections when that section's url is active is set based on the outdated url/href, and the section that's expected to be expanded is closed.

I think the best solution to this problem could be swap out the <Link> for a <StyledLink> (using a regular <a> instead of next's custom anchor) and then to change the onRouteChange in DocsLayout to listen for a url/href update, either how @kitten  suggested in 143 or via a listener on window.location instead of calling it on click of certain links.  This second step may have implications beyond just this component though.  Thoughts?

**Comment by el1f** [comment]
This doesn't seem to be relevant anymore, does it? The Sidebar always seems to link to the correct target regardless of its contents
