### ISSUE TITLE
Add OpenCollective sponsors to homepage

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#229]
Now that we have an [OpenCollective](https://opencollective.com/styled-components) we should add all sponsors' logos (i.e. folks who contribute 200$+) to the homepage, probably at the bottom below the introductory explanation.

OpenCollective has an API that gives you all the members: https://opencollective.com/styled-components/members/all.json?tierId=3278

**Comment by osamajandali** [comment]
I will be happy to do this 😎

**Comment by mxstbr** [comment]
Awesome, looking forward to the PR!

**Comment by osamajandali** [comment]
I'm thinking about the design like this, just adding the logos linked:
![stlyed](https://user-images.githubusercontent.com/13832392/35532087-a8a70d0e-0541-11e8-8833-7694d20ba187.jpg)

or should we make it like backers version ?

**Comment by mxstbr** [comment]
No I like that! 👌

**Comment by osamajandali** [comment]
This is done just couple of things need your opinion : 
- The text under the sponsors title
- I designed a svg that is rendered when there is no image on the sponsor profile instead of blank photo.
<img width="1002" alt="screen shot 2018-02-03 at 9 02 19 pm" src="https://user-images.githubusercontent.com/13832392/35770560-5effc888-0926-11e8-969c-66fdc21b2cfc.png">

- Should I add loading animation until the requests finishes?
- Should I show error message on the site when the request fails or just have it console logged?

Also, OpenCollective API doesn't have Access-Control-Allow-Origin header within styled component API, take a look at this https://github.com/opencollective/opencollective/issues/342

**Comment by mxstbr** [comment]
Looking great! I assume most sponsors will be companies, I think we should filter out the core team from those.

/cc @xdamman

**Comment by mxstbr** [comment]
But why is the core team part of the Sponsor tier then? :thinking: None of us sponsor styled-components

**Comment by osamajandali** [comment]
I think a config should be there to categories the sponsors.
Take a look at [babel open collective](https://opencollective.com/babel/), they have sponsors categories and if you take a look at their [API](https://opencollective.com/babel/members/all.json), they have tier key in the sponsor object and in styled component API doesn't have.

**Comment by mxstbr** [comment]
We have a "Sponsor" tier and a "Backer" tier: https://opencollective.com/styled-components/

<img width="332" alt="screen shot 2018-02-04 at 15 04 48" src="https://user-images.githubusercontent.com/7525670/35778310-c40bd3ca-09bc-11e8-8d61-6c20c685c6b2.png">

I want to display the Sponsors on the homepage.

**Comment by xdamman** [comment]
It's because it should be `TierId` and not `tierId` as the query parameter.

**Comment by adaynit** [comment]
I would like to contribute to this. Could you tell me where I can access your homepage on the GitHub?

**Comment by mxstbr** [comment]
@adaynit unfortunately, @osamajandali is already working on this in #230!

**Comment by morajabi** [comment]
@adaynit Actually, this is the repo for the homepage 😅 Feel free to grab other issues! 👍

**Comment by mckernanin** [comment]
@osamajandali need any help with #230 ?

**Comment by osamajandali** [comment]
@mckernanin Thank you ! I have finished it out back then but @kitten have issues on it that I need more details on it. 
Maybe the reviewers are busy with some other stuff that's why I was on holding state.
