### ISSUE TITLE
LiveEdit overflow

### ISSUE THREAD

**Issue by pavelsuraba** [styled-components/styled-components-website#4]
Hey guys, I have a proposition to improve docs.
In Regards to LiveEdit components where you can scroll inside.

The problem is when you scroll over top or bottom inside LiveEdit component, then you scroll with the whole page and you mess up your scroll position. Which seems super annoying to me.

Here is a demo if you don't know what I mean.
http://codepen.io/pavelsuraba/full/bWVoBO/

Anyway it's not hard to implement and I could fix that with HOC.

Would this change be welcomed?

Thanks.

**Comment by philpl** [comment]
@pavelsuraba that is definitely a possibility, I've implemented some scroll-blockers in the past.

The big trouble with them is: They don't work well AND solutions sometimes aren't cross-browser compatible.

Even in your solution, if you scroll a bit faster, the window "jumps". So I'm a bit reluctant to go ahead with this, because most of the time it's really time consuming :wink:

**Comment by philpl** [comment]
@pavelsuraba I must be mad since I started working on this anyway 😆 

https://github.com/styled-components/styled-components-website/pull/5

This currently improves the scroll blocker a little bit, by blocking as well, when the trajectory is aiming to overshoot the scroll area.

The only thing I'd like to add as well to this is to only scroll `window` when the scrolling originates from there. Otherwise we're blocking scrolling, even though the user just likes to scroll the page, and is accidentally hovering over an editor.

**Comment by pavelsuraba** [comment]
👍  looks good. I was wondering that I can't be the only one who finds this annoying.

**Comment by philpl** [comment]
@pavelsuraba I added the exceptions for when the window is being scrolled, and mobile. It'd be great if you could help me test it on multiple devices 😄

**Comment by pavelsuraba** [comment]
**@philpl** I am totally for sidebar as well.
I'll definitely take a look when I get a chance. From my experience touchpad and mouse works fine.
But mobile won't work since you use 'wheel' event. I don't consider it an issue, because it's not so bad on touch screen.

**Comment by philpl** [comment]
@pavelsuraba Yea, I added some code to explicitly disable it on mobile devices (< 1000px width), since the design of a lot of components change at that breakpoint to accommodate touch devices.

I guess I'll just merge it, and if sth goes wrong we can still open another issue
