### ISSUE TITLE
injectGlobal vs resetStyles in _document.js

### ISSUE THREAD

**Issue by pronevich** [styled-components/styled-components-website#54]
Is there some reason why you have used resetStyles object/string in _document.js instead injectGlobal() ?

**Comment by philpl** [comment]
Yes, a couple of things still misbehave since next.js has not added an API for wrapping the app yet: https://github.com/styled-components/styled-components-website/blob/master/pages/_document.js#L140

So some code is not migrated / changed yet and just there to "make things work". :wink: 😆

**Comment by pronevich** [comment]
Is there any drawbacks to use <ThemeProvider> for each page?

**Comment by philpl** [comment]
@pronevich this page is not using the ThemeProvider, but no. Apart from the duplication there's no harm. But repeating yourself is often bad practice, so it should be avoided.

I'm not sure whether you're referring to the stylesheet manager instead? It can't be repeated, since we need to inject the resulting style tags into the head of the document statically during SSR.

Please move questions unrelated to this site into a new issue on the SC repo :)
