### ISSUE TITLE
cannot select text in code examples in Firefox

### ISSUE THREAD

**Issue by stefanprobst** [styled-components/styled-components-website#560]
While selecting text in code examples works fine in Chrome 77, I cannot select text in Firefox 69. Not sure what the intended behavior is here -- but it looks like `pointer-events: none` on `<pre>` prohibits that (it works with unsetting pointer-events).

**Comment by el1f** [comment]
This is due to `react-live`, which is being used on both the interactive examples and the non-interactive examples. We should either move away from using that library for such examples or try and submit a PR to make the text in the code examples selectable even when the `disabled` prop is enabled on the editor.
Any thoughts on this @mxstbr?
