### ISSUE TITLE
Update z-index on small showcase site hover to prevent clipping.

### ISSUE THREAD

**Issue by justinjunodev** [styled-components/styled-components-website#674]
Hey Styled Components Friends! 👋

I noticed that the "Small Showcase" on the home page has a couple of issues when hovered. 

![clipped-showcase](https://user-images.githubusercontent.com/50022106/87362377-16d12d00-c534-11ea-9ed2-e8263c87118a.png)

1. The first is that when a site is hovered, the label is sometimes clipped by the site thumbnail resting in front of it.

2. There isn't a cursor/ pointer shown when a site is hovered. While the majority of users probably know they can click through, others may not and think that their only option to see or learn more is by clicking the discover more button below. 

That said, I've created a pull request that basically applies the opposite z-index and a cursor when hovered. This way the hovered site will be move to the top and will be readable, etc. I'll reference in the comments below. 

Thanks in advance for your time and support.

**Comment by el1f** [comment]
Hello there @justinjunodev! Thanks for your contribution, I've definitely left it kinda confusing there 😅
I definitely agree when it comes to the current implementation lacks a lot in the way of usability and that piece of IMDB label sneaking down the Spotify screenshot is hurting my eyes quite a lot. That being said, I'm not a great fan of the clipping that happens when you switch the z-index as it breaks the illusion of depth that that disposition is trying to create :/
Maybe we should experiment by having the labels float to the left on the left showcased websites and to. the right on the right ones?

Something like this:
![image](https://user-images.githubusercontent.com/10723208/87366540-3a6a9680-c579-11ea-86b9-2d9460c2249f.png)

What do you think about it?

Moving on, definitely agree with _2._ and I thank you a lot for pointing that out, completely went around my radar.

Thanks for the time you took into filing this issue!

**Comment by justinjunodev** [comment]
For sure and no worries. I completely agree about the depth and am definitely open to moving the labels. I've got to get my little ones to bed, but will do some experimenting in the morning. 👍

**Comment by justinjunodev** [comment]
Good morning @el1f. Removed the z-index, updated the transform properties to prevent clipping, and left the cursors as described. Feel free to check it out and let me know if this more inline with what you are thinking. [More info here](https://github.com/styled-components/styled-components-website/pull/675)
