### ISSUE TITLE
Write "Motivation" section

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#81]
This is 100% on me, rather than just link to my talk we should have an actual "Motivation" section.

**Comment by morajabi** [comment]
And no one can do this as good as you :)

**Comment by probablyup** [comment]
Would a transcript be sufficient here, or is it better to compose a whole new section?

**Comment by PinkaminaDianePie** [comment]
@probablyup in ideal case it should be a whole new section, just because the text for articles and script for presentations are always a bit different.

@mxstbr ...but the transcript is better than nothing, if you don't have time to prepare this section from the scratch, someone could put transcript at least.

**Comment by el1f** [comment]
@mxstbr it seems like this is not relevant anymore :)
https://www.styled-components.com/docs/basics#motivation

**Comment by mxstbr** [comment]
Yep this is done!
