### ISSUE TITLE
Translation tooling

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#86]
With the volunteers in #70 and the changes in #74 the content is now in a markdown string and we should now be able to start translating the webpage.

React uses https://crowdin.com, which seems pretty good in terms of the workflow for translators and they offer a free unlimited account to OSS projects. What I'm not sure about is the workflow from the development side; how are changes going to get on the website, which format do the strings need to have, etc.

On top of that I'm not sure how we'd make that happen across the app, how we'd structure the repo, etc.

Any investigations/experiences here very helpful.

**Comment by victorhqc** [comment]
I'm gonna post a PR soon about this. Gonna be using [this](https://github.com/i18next/react-i18next) and dummy translations just as a start point.

**Comment by mxstbr** [comment]
Awesome, can't wait!

**Comment by el1f** [comment]
Hey @kitten! I checked out #148 and it seems like a lot of work had been done but it was closed due to the absence of a clear focus on what the translation system would need to achieve structure-wise. Are we now in a clearer place to reopen the conversation regarding this extremely interesting feature?
